baseURL = 'https://extraordinary-dango-83098d.netlify.app/'  # change after deploying site
languageCode = 'en-us'
title = 'Hugo and Netlify CMS'
theme = 'ananke'
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3
[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'